version: "3"
services:

  app-1:
    image: ahmedfaroukamir/docker_images:javaappimage1.1
    ports:
     - "9081:8080"
    container_name: app1c
    networks:
      - frontend
 
  app-2:
    build: ./app2
    ports:
      - "9082:8080"
    container_name: app2c
    networks:
      - frontend
 

  reverseproxy:
    image: ahmedfaroukamir/docker_images:reverseproxy1.1
    ports:
      - "9085:80"
    links:
      - app-1
      - app-2
    container_name: reverseproxy1container
    networks:
      - frontend

networks:
  frontend:
          #driver: custom-driver-1
